sudo: false
language: python
python: "2.7"
cache:
  directories:
  - "${HOME}/google-cloud-sdk/"
env:
  - PATH=${HOME}/google-cloud-sdk/bin:$PATH CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash ; fi
  - gcloud components update --version 137.0.0
  - gcloud components install app-engine-python
install:
  - pip install . flake8 funcsigs
script:
  - flake8 .
  - python manage.py test -v 2
