language: python
python: "2.7"
before_install:
  - sudo apt-get -qq install wget
  - pushd $HOME
  - wget -O google-cloud-sdk.tgz https://storage.googleapis.com/cloud-sdk-release/google-cloud-sdk-148.0.1-linux-x86_64.tar.gz
  - tar -zxpf google-cloud-sdk.tgz
  - rm google-cloud-sdk.tgz
  - popd
  - $HOME/google-cloud-sdk/install.sh --usage-reporting=true --path-update=true --bash-completion=true --rc-path=$HOME/.bashrc --additional-components app-engine-python
  - export PATH=$HOME/google-cloud-sdk/bin:$PATH
  - export PYTHONPATH=$PYTHONPATH:$HOME/google-cloud-sdk/platform/google_appengine
install:
  - pip install . flake8
script:
  - flake8 .
  - python manage.py test -v 2
